### ISSUE TITLE
Al borrar sede con salas, index de salas falla

### ISSUE THREAD

**Issue by Shinseiki86** [hgonzalezgaviria/diheke#1]
Al borrar una sede que tenga salas asignadas, el index de salas genera error "Trying to get property of non-object".

El error se produce porque al borrar la sede, no se borran las salas asociadas.
![image](https://cloud.githubusercontent.com/assets/22685115/24737049/7fa84296-1a51-11e7-992f-559e2ecb5ad3.png)

**Comment by Shinseiki86** [comment]
El mismo error se produce al borrar roles con usuarios asociados.

**Comment by hgonzalezgaviria** [comment]
Se agrega validación en el controlador, se realiza igual para salas y equipos
